<a href="https://colab.research.google.com/github/Korchomnyi-Ivan/Chiselni-Metodu/blob/main/%D0%9B_%D0%A0_4%2C_%D0%9A%D0%BE%D1%80%D1%87%D0%BE%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE_%D0%86%D0%B2%D0%B0%D0%BD%D0%B0_%D0%9C%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D0%B9%D0%BE%D0%B2%D0%B8%D1%87%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 4_1, Корчомного Івана Миколайовича, Група ФІТ 2-15. Тема: «Робота з матрицями»

In [ ]:
#Встaновити numpy
#!pip install numpy

In [ ]:
# Приклади роботи з матрицями
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
numpy_version


'2.0.2'

In [ ]:
#1.
matrix = np.random.randint(1, 6, size =(3, 3))

matrix

array([[4, 4, 3],
       [1, 4, 4],
       [2, 5, 2]])

In [ ]:
#2.
det = np.linalg.det(matrix)
det

np.float64(-33.0)

In [ ]:
#3.
product = np.prod(matrix)
product

np.int64(15360)

In [ ]:
#4.
sum = np.sum(matrix)
sum

np.int64(29)

In [ ]:
#5.
max_element = np.max(matrix)
print("Найбільший елемент матриці ", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці ", min_element)

Найбільший елемент матриці  5
Найменший елемент матриці  1


In [ ]:
# 6.
mean = np.mean(matrix)
mean

np.float64(3.2222222222222223)

In [ ]:
#7
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[2.        , 2.        , 1.73205081],
       [1.        , 2.        , 2.        ],
       [1.41421356, 2.23606798, 1.41421356]])

In [ ]:
# 8
row_suns = np.sum(matrix, axis = 1).reshape(-1, 1)
row_suns

array([[11],
       [ 9],
       [ 9]])

In [ ]:
# 9
vector = np.random.randint(0, 10, size = 25)
print("Початковий вектор:")
print(vector)
sorted_vector = np.sort(vector)[::-1]
print("Відсортований вектор:")
print(sorted_vector)

Початковий вектор:
[7 3 0 3 3 2 8 7 9 8 7 1 0 8 7 0 3 8 8 4 1 2 5 4 7]
Відсортований вектор:
[9 8 8 8 8 8 7 7 7 7 7 5 4 4 3 3 3 3 2 2 1 1 0 0 0]


In [ ]:
#10
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print(mode)
print(median)
print(mean)
print(max_value)
print(min_value)

ModeResult(mode=np.int64(7), count=np.int64(5))
4.0
4.6
9
0


In [ ]:
# 11
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

matrix_sum = matrix1 = matrix2
matrix_diff = matrix1 = matrix2
matrix_product = matrix1 = matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)

Матриця 1:
[[4 1 9 7]
 [7 2 1 3]
 [6 5 7 1]
 [5 6 2 2]]

Матриця 2:
[[ 3  6  4  4]
 [ 4  5  4  5]
 [ 6  6  1  2]
 [ 5 10  2 10]]

Сума матриць:
[[ 3  6  4  4]
 [ 4  5  4  5]
 [ 6  6  1  2]
 [ 5 10  2 10]]

Різниця матриць:
[[ 3  6  4  4]
 [ 4  5  4  5]
 [ 6  6  1  2]
 [ 5 10  2 10]]

Поелементний добуток матриць:
[[ 3  6  4  4]
 [ 4  5  4  5]
 [ 6  6  1  2]
 [ 5 10  2 10]]


In [ ]:
# 12
x = np.arange(9.0)
x


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
#13.1
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [ ]:
# 13.2
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1**x2

array([ 0,  1,  8, 27, 16,  5])

Висновок: Виконуючи дану лабораторну роботу, я покращив свої навички роботи із матрицями у коді.